<?php

namespace AppBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
  public function findEvenementsBytitre($motcle){
    $query = $this ->createQueryBuilder('f')
      ->where('E.nom like :nom')
      ->setParameter('nom', $motscle. '%')
      ->orderBy('E.nom', 'ASC')
      ->getQuery();

      return $query->getResult();
  }
}
